apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-catalog-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: fcg-catalog-api

  template:
    metadata:
      labels:
        app: fcg-catalog-api

    spec:
      containers:
        - name: fcg-catalog-api
          image: GabrielNatan2001/fcg-catalog-api:latest

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: fcg-catalog-api-config
            - secretRef:
                name: fcg-catalog-api-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
