apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-catalog-api-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  Jwt__Issuer: FCG.Users.API
  Jwt__Audience: FCG.Client
  MessageBusConfigs__RetryCount: "5"
  Publishers__OrderPlaced__Exchange: fcg.order.placed
  Publishers__OrderPlaced__RoutingKey: payments.order-placed
  MongoDB__Database: fcg_catalog
  Cache__JogosTtlSeconds: "60"
