apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-catalog-api-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  MessageBusConfigs__RetryCount: "5"
  Publishers__OrderPlaced__Exchange: fcg.order.placed
  Publishers__OrderPlaced__RoutingKey: payments.order-placed
  MongoDB__Database: fcg_catalog
  Cache__JogosTtlSeconds: "60"
  OTEL_SERVICE_NAME: fcg-catalog-api
  OTEL_EXPORTER_OTLP_ENDPOINT: http://fcg-otel-collector:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
