apiVersion: v1
kind: Secret
metadata:
  name: fcg-catalog-worker-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=fcg-postgres;Port=5435;Database=fcg_catalog;Username=postgres;Password=postgres
  MessageBusConfigs__Host: amqp://admin:admin@fcg-rabbitmq:5672/
