// <auto-generated />
using System;
using FCG.Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCG.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FCG.Catalog.Domain.Biblioteca.Entities.BibliotecaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("bibliotecas", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Biblioteca.Entities.ItemBibliotecaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BibliotecaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_aquisicao");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogo_id");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("BibliotecaId", "JogoId")
                        .IsUnique();

                    b.ToTable("itens_biblioteca", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Jogo.Entities.JogoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("jogos", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Pedidos.Entities.PedidoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Biblioteca.Entities.ItemBibliotecaEntity", b =>
                {
                    b.HasOne("FCG.Catalog.Domain.Biblioteca.Entities.BibliotecaEntity", null)
                        .WithMany("Itens")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCG.Catalog.Domain.Jogo.Entities.JogoEntity", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("FCG.Catalog.Domain.Biblioteca.Entities.BibliotecaEntity", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
